version: "3"
services:
  acme-explorer:
    build: .
    restart: on-failure
    ports:
     - "127.0.0.1:${PORT}:8080"
    depends_on:
      - mongo
    environment: 
      - NODE_ENV=${NODE_ENV} 
      - PORT=${PORT}   
      - mongoDBPort=${DBPORT}     
      - VIRTUAL_HOST=${VIRTUAL_HOST}   
      - VIRTUAL_PORT=${VIRTUAL_PORT}   
      - mongoDBHostname=mongo
  mongo:
    image: mongo
    environment: 
      - DBPORT=${DBPORT}
    expose:
      - "${DBPORT}"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:

networks:
  default:
    external: 
      name: service-tier